Browser support and JS Guidelines Cleanup
inrupt/public-documentation pull request #12
Opened 2020-10-30 13:43 UTC by ajacksified

* Add browser support guidelines
* Add guideline to use https://github.com/inrupt/javascript-style-configs for linting
* Clarify rules that require documented decisions
  * Change test file recommendation to put tests alongside src files (as currently implemented in solid-client libraries and pod browesr)
  * Compiled src should go to `dist`
  * Clarify that apps use Next.js / webpack, and js / ts libraries use rollup
  * Replace Travis with Github Actions for CI
  * Suggest LogLevel for logs
* Clean up whitespace (soft max-length line of 100; remove spaces at the end of lines; 2-space tabs; etc)

2020-11-02 14:59 UTC, kevin-inrupt commented on coding-conventions/javascript-coding-standards.md
> +    -  Edge
I would explicitly say "Edge (Chromium)"

2020-11-02 15:00 UTC, ajacksified commented on coding-conventions/javascript-coding-standards.md
> +    -  Edge
Wouldn't "latest two versions" cover chromium?

2020-11-02 15:03 UTC, kevin-inrupt commented on coding-conventions/javascript-coding-standards.md
> +  - Desktop:
As with the Mobile browsers, do we want to be explicit on the browser/OS combinations:
- Chrome / macOS, Ubuntu, and Windows
- Edge (Chromium) / macOS and Windows
- Firefox / macOS, Ubuntu, and Windows
- Safari / macOS

2020-11-02 15:05 UTC, kevin-inrupt requested changes
Commented on browser support guidelines.

2020-11-02 15:47 UTC, kevin-inrupt commented on coding-conventions/javascript-coding-standards.md
> +    -  Edge
Edge (edgeHTML) and Edge (Chromium) are 2 separate products, and it seems as if Microsoft treat the former still as a live product. Probably doesn't make any much of a difference (who uses the edgeHTML version??) but... Your call.

2020-11-02 15:51 UTC, ajacksified commented on coding-conventions/javascript-coding-standards.md
> +    -  Edge
Fair enough, I'll call out Chromium.

2020-11-02 17:08 UTC, oolivo submitted a review, later dismissed
LGTM

2020-11-03 07:52 UTC, kay-kim reviewed
Heh - I wasn't sure if people just wanted me to look at the browser support or to review other stuff.  I made a few notes on other stuff because I wasn't sure.  Like, we're not particularly parallel in sentence constructs, but wasn't sure if that was of any interest for this doc.

2020-11-03 07:52 UTC, kay-kim commented on coding-conventions/javascript-coding-standards.md
> +  - Not only ensure that code is used, but that its effects are tested.
? so that the form is ensure not only this but that.

```suggestion
Ensure not only that the code is used, but that is effects are tested.
```

2020-11-03 07:52 UTC, kay-kim commented on coding-conventions/javascript-coding-standards.md
> +  - Since each has one specific responsibility, integration tests check how those responsibilities
By "each" do you mean, each class/function?

2020-11-03 07:52 UTC, kay-kim commented on coding-conventions/javascript-coding-standards.md
> +  native methods return `any`, like `JSON.parse` -  those to a known type as soon as possible, preferably
missing a verbe before "those"?

2020-11-03 15:59 UTC, kevin-inrupt approved these changes

2020-11-03 16:33 UTC, pmcb55 commented on coding-conventions/javascript-coding-standards.md
> +  - Ensure not only that the code is used, but that is effects are tested.
```suggestion
  - Ensure not only that the code is used, but that its effects are tested.
```

2020-11-03 16:34 UTC, pmcb55 commented on coding-conventions/javascript-coding-standards.md
> +  1. Put source code on the `src` folder.
```suggestion
  1. Put source code in the `src` folder.
```

2020-11-03 16:39 UTC, pmcb55 commented on coding-conventions/javascript-coding-standards.md
> +  3. Add non-default export to an index file, ensuring that tree-shaking is possible with the `sideEffects` flag in `package.json`.
Maybe an example snippet  - i.e. I have no idea if it's:
```
{
  sideEffects: true  // Or is it false!
}
```
Or just link to the WebPack docs: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
And is this only relevant for WebPack ('cos we use both Parcel and Rollup now too!)...?

2020-11-03 16:40 UTC, pmcb55 commented on coding-conventions/javascript-coding-standards.md
> +5. Marking everything API that\'s intended for internal use but is externally accessible as `@internal` in its TSDoc, and
```suggestion
5. Annotate everything in the API that\'s intended for internal use, but is externally accessible, as `@internal` in its TSDoc, and
```

2020-11-03 16:41 UTC, pmcb55 commented on coding-conventions/javascript-coding-standards.md
> +  1. Put tests next to src files. In libraries, this is typically done by having a `foo.ts` and `foo.test.ts`
```suggestion
  1. Put tests next to source files. In libraries, this is typically done by having a `foo.ts` and `foo.test.ts`
```

2020-11-03 16:44 UTC, pmcb55 commented on coding-conventions/javascript-coding-standards.md
> +  1. Generate minified and non-minified versions.
Is it worth showing simple guidance (or a `package.json` snippet, or whatever) to show how ('cos I don't know!)...?

2020-11-03 16:44 UTC, pmcb55 commented on coding-conventions/javascript-coding-standards.md
> +  2. Ensure that all generated versions export a mapping file.
Is it worth showing simple guidance (or a `package.json` snippet, or whatever) to show how ('cos I don't know!)...?

2020-11-03 16:46 UTC, pmcb55 commented on coding-conventions/javascript-coding-standards.md
> +15. When including logging, use loglevel.
```suggestion
15. When including logging, use [loglevel](https://www.npmjs.com/package/loglevel).
```

2020-11-03 16:52 UTC, pmcb55 submitted a review, later dismissed
LGTM (just a few minor suggested tweaks).

2020-11-05 17:16 UTC, kevin-inrupt approved these changes

2020-11-05 17:53 UTC, pmcb55 approved these changes
LGTM

2020-11-05 18:25 UTC, merged